spring:
  application:
    name: mybill

  # 配置数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybill?rewriteBatchedStatements=true
    username: root
    password: mysql


mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler # 枚举类型处理器，新版本mybatisplus可以不指定
  global-config:
    db-config:
      logic-delete-field: deleteFlag # 全局逻辑删除的实体类字段名，字段类型可以是boolean、integer
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


knife4j:
  enable: true
  openapi:
    title: 用户管理接口文档
    description: "用户管理接口文档"
    email: zhanghuyi@itcast.cn
    contact: 虎哥
    url: https://www.itcast.cn
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.icu.mybatisplus.controller

springdoc:
  api-docs:
    enabled: true # 开启OpenApi接口
    path: /user-service/v3/api-docs  # 自定义路径，默认为 "/v3/api-docs"
  swagger-ui:
    enabled: true # 开启swagger界面，依赖OpenApi，需要OpenApi同时开启
    path: /user-service/swagger-ui/index.html # 自定义路径，默认为"/swagger-ui/index.html"


# ---------- 下面是自定义配置 ----------
com:
  icu:
    fileStoreDir: D:/files/
    token:
      # token 密钥 ： mybill-token-secret
      secret: bXliaWxsLXRva2VuLXNlY3JldA==
      expire-time: 259200 # token 过期时间，单位为分钟，259200=60*24*180

